all:

	(cd timerLib && make install)
	(cd 1-led && make)
	(cd 3* && make)
	(cd 8* && make)
	(cd 11* && make)



clean:

	(cd timerLib && make clean)

	(cd 1-led && make clean)
	(cd 3* && make clean)
	(cd 8* && make clean)
	(cd 11* && make clean)

	rm -rf h lib
